### ISSUE TITLE
Issue in production

### ISSUE THREAD

**Issue by thisissmohan** [moopsyjs/boilerplate#1]
I followed everything from documentation.

After i build, `npx moopsy bundle` and `cd bundle && node start.js`  i tried to access the frontend http://localhost:3001, but it returns **Cannot GET /**, but it is accessible while in development. issue is only with bundle.

Can you please help me to How/ Where i can access frontend? Also how we can pass environment variables?

**Comment by HiylloAdmin** [comment]
Thanks for the report, fixed in: [e3a3ff2](https://github.com/moopsyjs/boilerplate/commit/e3a3ff26f1c532b96b4137e749689b6f75021ba0)
